# Generated by Django 3.1.6 on 2021-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logotype', models.ImageField(blank=True, default='pricer_default.jpg', null=True, upload_to='', verbose_name='Картинки')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='pricer_default.jpg', null=True, upload_to='', verbose_name='Картинки')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('category', models.CharField(blank=True, choices=[('metal', 'metal'), ('not_metal', 'not_metal')], max_length=40, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
