# Generated by Django 3.1.6 on 2021-02-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logotype', models.ImageField(blank=True, default='pricer_default.jpg', null=True, upload_to='', verbose_name='Картинки')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.firm', verbose_name='Продукты'),
        ),
    ]
