# Generated by Django 3.1.6 on 2021-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210218_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_product',
            field=models.CharField(default=1, max_length=40, unique=True, verbose_name='Модел'),
            preserve_default=False,
        ),
    ]
