# Generated by Django 3.1.6 on 2021-02-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210218_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='quantity',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.TextField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.firm', verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.productmodel', verbose_name='Модель'),
        ),
    ]
