# Generated by Django 3.1.6 on 2021-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210218_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.TextField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
