# Generated by Django 3.1.6 on 2021-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210218_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество'),
        ),
    ]
