# Generated by Django 3.1.6 on 2021-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20210218_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='logotype',
            field=models.ImageField(blank=True, default='pricer_default.jpg', null=True, upload_to='', verbose_name='Логотип'),
        ),
    ]
