# Generated by Django 3.1.6 on 2021-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20210218_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стоимость'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_model',
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ManyToManyField(blank=True, null=True, to='Products.ProductModel', verbose_name='Модель'),
        ),
    ]
