# Generated by Django 3.1.6 on 2021-02-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_auto_20210218_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ManyToManyField(blank=True, to='Products.ProductModel', verbose_name='Модель'),
        ),
    ]
